language: en

policies:
  - name: MemoizationPolicy
  - name: EmbeddingPolicy
    max_history: 5
    epochs: 500
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: "action_default_fallback"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "CRFEntityExtractor"
- name: "SpacyFeaturizer"
- name: "SklearnIntentClassifier"
- name: "EntitySynonymMapper"
